theme: jekyll-theme-architect
show_downloads: true
github.zip_url: https://github.com/GraceTHD-community/GraceTHD-sandbox/zipball/master
github.tar_url: https://github.com/GraceTHD-community/GraceTHD-sandbox/tarball/master
